modLoader="javafml"
loaderVersion="[51,)"
license="CC0-1.0"
issueTrackerURL="https://example.invalid/"

[[mods]]
modId="mire_and_peat"
version="${file.jarVersion}"
displayName="Mire & Peat"
description="Farm peat from mire!"
authors="3TUSK"
credits=""

[[dependencies.mire_and_peat]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"